### ISSUE TITLE
Fails during initialization in FreeCAD 0.18.1

### ISSUE THREAD

**Issue by burbilog** [kreso-t/FreeCAD_Mod_Adaptive_Path#1]
~~~
During initialization the error Missing parentheses in call to 'print'. Did you mean print("Nesting info: " , nesting)? (OpExecute.py, line 126) occurred in /home/rm/.FreeCAD/Mod/FreeCAD_Mod_Adaptive_Path/InitGui.py
~~~

Python2 -> to python3 problem?

**Comment by kreso-t** [comment]
sorry for late reply, did not notice this. 

yes, probably it was python version issue. However this python version is not maintained anymore, adaptive op was included in freecad master
